server:
  port: 8083
spring:
  application:
    name: ticket
  datasource:
    url: jdbc:mysql://10.0.0.130:3306/ticket
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  rabbitmq:
    host: 10.0.0.130
    port: 5672
    username: guest
    password: guest
    virtual-host: docker-mq-vhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://group1:111111@localhost:8761/eureka/

axon:
  distributed:
    enabled: true
  amqp:
    exchange: Group1.EventBus

